name: CI

on:
  push:
  pull_request:

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm install

      - name: ESLint
        run: npm run lint

      - name: Prettier
        run: npm run format:check

      - name: Validate JSON
        run: npm run validate:json
