name: Deploy static content to Pages (prod)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "pages-prod"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # If you have a build step, run it here (npm run build, etc.)
      # - run: |
      #     npm ci
      #     npm run build

      - name: Deploy to gh-pages (root)
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .               # change to your build output folder if needed
          clean: true             # wipe old files in root (production)
          commit-message: "prod: ${{ github.sha }}"

      - name: Prod URL
        run: |
          echo "Prod: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/" >> $GITHUB_STEP_SUMMARY
